
spring:

  devtools:
    livereload:
      enabled: true

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 7875
    driver-class-name: org.postgresql.Driver



     #session:
      #  store-type: redis

      #redis:
       # host: 127.0.0.1
       # port: 6379


logging:
  level:
    org.security : debug
    org.security.oauth2 : debug
    org.hibernate : info
    com.example.demo : debug

server:
  port: 80


security:
  user:
    name: iu
    password: palette






#security:

 # oauth2:
  #  resource:
   #   id: my_api

    #client:
     # client-id: trusted_app
      #client-secret: secret

#oauth:
 # megazone:
  #  clientId : J3LgUqKshaDEm_NvK4gx
   # clientSecret : SbEagQbVrd
    #callbackURL : http://localhost/oauth/callback/megazone



