

GET http://192.168.0.3:80/

###

POST http://192.168.0.3:80/app-api/member/update/access
Content-type : application/json

{
    "email" : "jang@lycos.co.kr",
    "accessCode" : "1111"
}

###


POST http://192.168.0.3:80/app-api/member/login?email=jang@naver.com&password=12345678&deviceType=Android&pushId=APA91bHanYjeMLlpaQKKw_eLY7c95HHlUUpdvxoFsxwIZEB-kvM7nsjKELERRqRJYOVvwRgjd2mFgUAtjg4RRfXU9g519No6ct5_fnHU-C7juRxPZkUFz8_OOUcFEvCN9fGiLXE2HBo5&deviceId=APA91bHanYjeMLlpaQKKw_eLY7c95HHlUUpdvxoFsxwIZEB-kvM7nsjKELERRqRJYOVvwRgjd2mFgUAtjg4RRfXU9g519No6ct5_fnHU-C7juRxPZkUFz8_OOUcFEvCN9fGiLXE2HBo5&nation=ko&accessCode=1234


###


GET http://192.168.0.3:80/app-api/board/news

###


GET https://www.starcoin.tv/app-api/app/version

###


GET http://192.168.0.3:80/api/test

###

GET http://192.168.0.3:80/api/admin

###



GET http://192.168.0.3:80/api/hello

###



GET http://192.168.0.3:80/token/test2

###



GET http://192.168.0.3:80/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibXlfYXBpIl0sInVzZXJfbmFtZSI6ImFkbWluIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIiwidHJ1c3QiXSwiZXhwIjoxNTE2OTI3NzQzLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImNjYjJhMjJlLTkyNGMtNDg4MS04NWJmLTU4OTc3MzViZjdlZiIsImNsaWVudF9pZCI6InRydXN0ZWRfYXBwIn0.ITNvoWYyHeXYNFBf9qp58VOFMTvCz0IF1c-Tj1q6KBw

###


GET http://192.168.0.60

###


GET http://jangseung-youi-iPhone.local

###